services:
  surefinsync:
    build: .
    container_name: surefinsync
    env_file:
      - .env
    volumes:
      - ${TRANSACTIONS_DIR}:/data/transactions
      - ${MERGED_TRANSACTIONS_DIR}:/data/merged
    tty: true
    entrypoint: ["python", "-m", "src.cli"]